concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'old_branch'
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I am run!"
